[build]
  command = "npm run build"
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "22"
  SECRETS_SCAN_OMIT_PATHS = "node_modules/**"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/blobs"]
